spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/auth-test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Mysql@123
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 120000
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  oauth2:
    storeType: jwt
